### PR TITLE
RAT-321: Play around with new configurability options / requires 0.16

### PR DESCRIPTION
**Pull request by ottlinger**
When I use 0.16-SNAPSHOT instead of 0.15 LICENSE fails the build:

```
*****************************************************
Summary
-------
Generated at: 2023-10-21T22:54:35+02:00

Notes: 1
Binaries: 0
Archives: 0
Standards: 14

Apache Licensed: 2
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

0 Unknown Licenses

*****************************************************

Files with unapproved licenses:

  LICENSE

*****************************************************

*****************************************************
  Files with Apache License headers will be marked AL
  Binary files (which do not require any license headers) will be marked B
  Compressed archives will be marked A
  Notices, licenses etc. will be marked N
  GPL3  pom.xml
  GPL3  src/main/java/de/aikiit/mailclena/MailClenaParameterParser.java
  GPL3  src/main/java/de/aikiit/mailclena/MailConfiguration.java
  GPL3  src/main/java/de/aikiit/mailclena/mail/MailClient.java
  GPL3  src/main/java/de/aikiit/mailclena/MailClena.java
  GPL3  src/test/java/de/aikiit/mailclena/MailClenaParameterParserTest.java
  GPL3  src/test/java/de/aikiit/mailclena/MailClenaTest.java
  GPL3  src/test/java/de/aikiit/mailclena/MailConfigurationTest.java
  GPL3  src/test/java/de/aikiit/mailclena/MailClenaCommandLineOptionsTest.java
  GPL3  src/test/java/de/aikiit/mailclena/mail/MailClientCommandsTest.java
  GPL3  src/test/java/de/aikiit/mailclena/mail/MailClientTest.java
 !N     LICENSE
  AL    mvnw
  AL    mvnw.cmd
  GPL3  .gitattributes
 
*****************************************************
```

### CODE REVIEW

**Comment by ottlinger** [comment]
Running with 0.15 on master yields the following rat.txt:
```
*****************************************************
Summary
-------
Generated at: 2023-10-21T22:59:59+02:00

Notes: 1
Binaries: 0
Archives: 1
Standards: 16

Apache Licensed: 3
Generated Documents: 0

JavaDocs are generated, thus a license header is optional.
Generated files do not require license headers.

0 Unknown Licenses

Archives:

 + .mvn/wrapper/maven-wrapper.jar
 
*****************************************************
  Files with Apache License headers will be marked AL
  Binary files (which do not require any license headers) will be marked B
  Compressed archives will be marked A
  Notices, licenses etc. will be marked N
  AL    .mvn/wrapper/maven-wrapper.properties
  A     .mvn/wrapper/maven-wrapper.jar
  GPL3  .mvn/maven-wrapper.properties
  GPL3  pom.xml
  GPL3  src/main/java/de/aikiit/mailclena/MailClenaParameterParser.java
  GPL3  src/main/java/de/aikiit/mailclena/MailConfiguration.java
  GPL3  src/main/java/de/aikiit/mailclena/mail/MailClient.java
  GPL3  src/main/java/de/aikiit/mailclena/MailClena.java
  GPL3  src/test/java/de/aikiit/mailclena/MailClenaParameterParserTest.java
  GPL3  src/test/java/de/aikiit/mailclena/MailClenaTest.java
  GPL3  src/test/java/de/aikiit/mailclena/MailConfigurationTest.java
  GPL3  src/test/java/de/aikiit/mailclena/MailClenaCommandLineOptionsTest.java
  GPL3  src/test/java/de/aikiit/mailclena/mail/MailClientCommandsTest.java
  GPL3  src/test/java/de/aikiit/mailclena/mail/MailClientTest.java
  N     LICENSE
  AL    mvnw
  AL    mvnw.cmd
  GPL3  .gitattributes
 
*****************************************************
```

**Comment by Claudenw** [comment]
I think the issue is that if the document is not a RAT_DOCUMENT_CATEGORY_VALUE_STANDARD document then it should not be evaluated for license approval pass/fail.  This means that unknown, archive, notice, and binary types should not be evaluated.  

Is this a correct analysis?

**Comment by Claudenw** [comment]
I found the issue in the DefaultPolicy class.  I will create a pull request to fix it.

**Comment by Claudenw** [comment]
To build from scratch you will need to build the jars and install them in the local repository so that the later tests can find the test jars.  We can fix this by creating a project that contains the shared test jars.  But that will make this change much larger (I think).  See the github build modifications for the fix to see what I mean.

**Comment by ottlinger** [comment]
Works perfectly fine after changes brought in from https://github.com/apache/creadur-rat/pull/159 - thanks @Claudenw

**Comment by ottlinger** [comment]
Can only be merged once 0.16 is released

**Pull request closed without merging**
